# Generated by Django 3.0.7 on 2020-06-20 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(db_index=True)),
                ('date_updated', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('sap_id', models.CharField(blank=True, max_length=128, null=True)),
                ('loopback', models.CharField(blank=True, max_length=128, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=15, null=True)),
                ('host_name', models.CharField(blank=True, max_length=128, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator_networkdetails_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='updater_networkdetails_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'network_details',
                'ordering': ['mac_address'],
            },
        ),
    ]
