# Generated by Django 3.0.7 on 2020-06-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_detail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdetails',
            name='loopback',
        ),
        migrations.AddField(
            model_name='networkdetails',
            name='loop_back',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='networkdetails',
            name='host_name',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='networkdetails',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='networkdetails',
            name='sap_id',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
