# Generated by Django 3.0.7 on 2020-06-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_detail', '0002_auto_20200620_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdetails',
            name='mac_address',
            field=models.CharField(default='mac_11', max_length=17, unique=True),
            preserve_default=False,
        ),
    ]
