# Generated by Django 3.0.7 on 2020-06-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_detail', '0003_auto_20200620_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdetails',
            name='host_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
