# Generated by Django 3.0.7 on 2020-06-20 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('network_detail', '0004_auto_20200620_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdetails',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f157433a-fd48-4a87-b77c-27b13ecbb79c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
