# Generated by Django 3.0.7 on 2020-06-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_detail', '0005_auto_20200620_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdetails',
            name='id',
            field=models.UUIDField(default='e2fd8bc4571e4035b0b841d24e427032', editable=False, primary_key=True, serialize=False),
        ),
    ]
