# Generated by Django 3.0.7 on 2020-06-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_detail', '0006_auto_20200620_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdetails',
            name='id',
            field=models.UUIDField(default='a1dc57cd786147838c8ebde126d1e8ea', editable=False, primary_key=True, serialize=False),
        ),
    ]
